import { useState } from 'react';
import { FiLink, FiMic, FiPlus, FiZap } from 'react-icons/fi';
const nodeTypes = [['entity', '@Entity', 'Tabla relacional con PK UUID/Long', 'bg-indigo-400'], ['dto', 'DTO / Record', 'Transferencia API sin ORM overhead', 'bg-violet-400'], ['enum', 'enum', 'Estados, roles y catálogos', 'bg-amber-400'], ['embeddable', '@Embeddable', 'Componentes embebidos', 'bg-cyan-400']];
const relations = [['oneToMany', '@OneToMany', '1 : N'], ['manyToOne', '@ManyToOne', 'N : 1'], ['manyToMany', '@ManyToMany', 'N : M'], ['oneToOne', '@OneToOne', '1 : 1']];
export default function EditorToolbar({ onCreate, onRelation, onCommand, listening, onListen, nodes, edges, onGenerate }) {
  const [command, setCommand] = useState(''); const execute = () => { if (command.trim()) { onCommand(command); setCommand(''); } };
  return <aside className="flex h-full w-80 shrink-0 flex-col border-r border-[#1d2a4a] bg-[#0c152b] text-slate-200"><div className="border-b border-[#1d2a4a] p-3"><button onClick={() => onCreate('entity')} className="flex w-full items-center justify-center gap-2 rounded-lg border border-indigo-300/40 bg-indigo-500 px-3 py-3 text-sm font-bold text-white shadow-lg shadow-indigo-950/60 hover:bg-indigo-400"><FiPlus /> Nueva Clase / Entidad JPA</button></div><div className="flex-1 space-y-5 overflow-y-auto p-3 text-xs">
    <section><SectionTitle title="Paleta de nodos" hint="click para añadir" /><div className="grid grid-cols-2 gap-2">{nodeTypes.map(([kind, label, copy, color]) => <button key={kind} onClick={() => onCreate(kind)} className="rounded-lg border border-slate-700 bg-[#121d39] p-2.5 text-left transition hover:border-indigo-400 hover:bg-[#18264a]"><span className="flex justify-between font-bold"><span className="flex items-center gap-1.5"><i className={`h-2.5 w-2.5 rounded-full ${color}`} />{label}</span><small className="font-mono text-slate-400">{kind === 'entity' ? 'JPA' : 'Java'}</small></span><span className="mt-2 block leading-4 text-slate-400">{copy}</span></button>)}</div></section>
    <section><SectionTitle title="Relaciones JPA" hint="cardinalidad" />{relations.map(([type, label, card]) => <button key={type} onClick={() => onRelation(type)} disabled={nodes.length < 2} className="mb-2 flex w-full items-center justify-between rounded-lg border border-slate-700 bg-[#121d39] px-3 py-2.5 font-mono text-slate-300 hover:border-violet-400 disabled:opacity-40"><span className="flex items-center gap-2"><FiLink className="text-cyan-300" />{label}</span><b className="rounded bg-violet-800/70 px-2 py-0.5 text-violet-200">{card}</b></button>)}</section>
    <section className="rounded-xl border border-indigo-500/40 bg-[#111b35] p-3"><div className="mb-3 flex items-center justify-between font-bold text-indigo-200"><span className="flex items-center gap-2"><FiZap /> Agente IA de Modelado</span><span className="rounded-full bg-emerald-500/20 px-2 py-1 text-[10px] text-emerald-300">IA local</span></div><div className="flex rounded-lg border border-slate-600 bg-[#080f20] p-1"><input value={command} onChange={(e) => setCommand(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && execute()} placeholder="Crea entidad Pedido..." className="min-w-0 flex-1 bg-transparent px-2 text-xs outline-none placeholder:text-slate-500" /><button onClick={onListen} className={`rounded p-2 ${listening ? 'bg-rose-500 animate-pulse' : 'bg-indigo-700 hover:bg-indigo-600'}`} title="Comando de voz"><FiMic /></button></div><button onClick={execute} className="mt-2 w-full rounded bg-slate-800 px-2 py-2 text-left text-slate-300 hover:bg-slate-700">✨ Ejecutar instrucción</button></section>
    <section className="rounded-xl border border-slate-700 bg-[#101a31] p-3"><SectionTitle title="Generador Spring Boot" hint="4 capas" /><ul className="space-y-2 font-mono text-slate-400"><li>✓ 1. Entidades <small className="float-right">@Entity</small></li><li>✓ 2. Repositorios <small className="float-right">JpaRepository</small></li><li>✓ 3. Servicios <small className="float-right">@Service</small></li><li>✓ 4. Controladores <small className="float-right">@RestController</small></li></ul><button onClick={onGenerate} className="mt-4 w-full rounded-lg border border-indigo-400/40 bg-indigo-600 px-3 py-2 font-bold text-white hover:bg-indigo-500">Generar código</button></section>
  </div><div className="border-t border-[#1d2a4a] bg-[#0b1429] p-3"><div className="rounded-2xl border border-slate-700/80 bg-[#0a1328] p-3"><div className="mb-3 font-mono text-[11px] font-bold uppercase tracking-wide text-slate-400">Presencia en el lienzo</div><div className="space-y-3 text-xs"><div className="flex items-center gap-2"><i className="h-3 w-3 rounded-full bg-emerald-400 shadow-[0_0_8px_#34d399]" /><span className="flex-1 font-medium text-slate-200">Kelly R. <span className="text-slate-400">(Lead Architect)</span></span><span className="font-mono text-[10px] text-indigo-300">Lock: Proyecto.java</span></div><div className="flex items-center gap-2"><i className="h-3 w-3 rounded-full bg-sky-400 shadow-[0_0_8px_#38bdf8]" /><span className="flex-1 font-medium text-slate-200">Ing. Marcos <span className="text-slate-400">(Backend)</span></span><span className="font-mono text-[10px] text-slate-500">Lienzo general</span></div></div></div></div><div className="flex justify-between border-t border-[#1d2a4a] px-4 py-3 font-mono text-[11px] text-slate-500"><span>{nodes.length} Entidades • {edges.length} Relación{edges.length === 1 ? '' : 'es'}</span><span className="text-emerald-400">Auto-saved</span></div></aside>;
}
function SectionTitle({ title, hint }) { return <div className="mb-2 flex justify-between font-mono text-[11px] font-bold uppercase tracking-wide text-slate-400"><span>{title}</span><span className="normal-case text-indigo-400">{hint}</span></div>; }
