import { useState } from 'react';
import { FiLink, FiMic, FiPlus, FiZap } from 'react-icons/fi';

const nodeTypes = [['entity', '@Entity', 'Tabla relacional con PK UUID/Long', 'bg-indigo-400'], ['interface', '<<interface>>', 'Contrato Java para realización', 'bg-fuchsia-400'], ['dto', 'DTO / Record', 'Transferencia API sin ORM overhead', 'bg-violet-400'], ['enum', 'enum', 'Estados, roles y catálogos', 'bg-amber-400'], ['embeddable', '@Embeddable', 'Componentes embebidos', 'bg-cyan-400']];
nodeTypes.push(['class', 'Clase Java', 'Clase o clase abstracta', 'bg-slate-400']);
const relations = [
  ['asociacion', 'Asociación', 'línea sólida'],
  ['agregacion', 'Agregación', 'rombo blanco'],
  ['composicion', 'Composición', 'rombo negro'],
  ['herencia', 'Herencia', 'triángulo'],
  ['realizacion', 'Realización', 'trazo discontinuo'],
  ['dependencia', 'Dependencia', 'flecha discontinua'],
];

export default function EditorToolbar({ onCreate, onRelation, onCommand, listening, onListen, command: controlledCommand, onCommandChange, aiStatus = 'inactivo', aiMessage = '', aiPlan, onConfirmAi, onCancelAi, nodes, edges, onGenerate, generating = false, readOnly = false, canUseRelations = true, onlineMembers = [] }) {
  const [localCommand, setLocalCommand] = useState('');
  const command = controlledCommand ?? localCommand;
  const setCommand = onCommandChange || setLocalCommand;
  const busy = ['interpretando', 'aplicando'].includes(aiStatus);
  const execute = () => { if (command.trim() && !busy) onCommand(command.trim()); };
  return <aside aria-disabled={readOnly} className={`flex h-full w-80 shrink-0 flex-col border-r border-[#1d2a4a] bg-[#0c152b] text-slate-200 ${readOnly ? 'pointer-events-none opacity-45' : ''}`}>
    <div className="border-b border-[#1d2a4a] p-3"><button onClick={() => onCreate('entity')} className="flex w-full items-center justify-center gap-2 rounded-lg border border-indigo-300/40 bg-indigo-500 px-3 py-3 text-sm font-bold text-white shadow-lg shadow-indigo-950/60 hover:bg-indigo-400"><FiPlus /> Nueva Clase / Entidad JPA</button></div>
    <div className="flex-1 space-y-5 overflow-y-auto p-3 text-xs">
      <section><SectionTitle title="Paleta de nodos" hint="click para añadir" /><div className="grid grid-cols-2 gap-2">{nodeTypes.map(([kind, label, copy, color]) => <button key={kind} onClick={() => onCreate(kind)} className="rounded-lg border border-slate-700 bg-[#121d39] p-2.5 text-left transition hover:border-indigo-400 hover:bg-[#18264a]"><span className="flex justify-between font-bold"><span className="flex items-center gap-1.5"><i className={`h-2.5 w-2.5 rounded-full ${color}`} />{label}</span><small className="font-mono text-slate-400">{kind === 'entity' ? 'JPA' : 'Java'}</small></span><span className="mt-2 block leading-4 text-slate-400">{copy}</span></button>)}</div></section>
      {canUseRelations && <section><SectionTitle title="Relaciones UML" hint="Arrastra desde la parte hacia el todo." />{relations.map(([type, label, notation]) => <button key={type} onClick={() => onRelation(type)} disabled={nodes.length < 2} className="mb-2 flex w-full items-center justify-between rounded-lg border border-slate-700 bg-[#121d39] px-3 py-2.5 font-mono text-slate-300 hover:border-violet-400 disabled:opacity-40"><span className="flex items-center gap-2"><FiLink className="text-cyan-300" />{label}</span><b className="rounded bg-violet-800/70 px-2 py-0.5 text-[9px] text-violet-200">{notation}</b></button>)}</section>}
      <section className="rounded-xl border border-indigo-500/40 bg-[#111b35] p-3"><div className="mb-3 flex items-center justify-between font-bold text-indigo-200"><span className="flex items-center gap-2"><FiZap /> Agente IA de Modelado</span><span className="rounded-full bg-emerald-500/20 px-2 py-1 text-[10px] text-emerald-300">Agente IA</span></div><div className="flex rounded-lg border border-slate-600 bg-[#080f20] p-1"><input value={command} onChange={(e) => setCommand(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); execute(); } }} disabled={busy} placeholder="Crea entidad Pedido..." className="min-w-0 flex-1 bg-transparent px-2 text-xs outline-none placeholder:text-slate-500 disabled:opacity-60" /><button onClick={onListen} disabled={busy} className={`rounded p-2 disabled:opacity-40 ${listening ? 'bg-rose-500 animate-pulse' : 'bg-indigo-700 hover:bg-indigo-600'}`} title={listening ? 'Detener reconocimiento de voz' : 'Comando de voz'}><FiMic /></button></div><button onClick={execute} disabled={busy || !command.trim()} className="mt-2 w-full rounded bg-slate-800 px-2 py-2 text-left text-slate-300 hover:bg-slate-700 disabled:opacity-45">{aiStatus === 'interpretando' ? 'Interpretando…' : aiStatus === 'aplicando' ? 'Aplicando…' : '✨ Ejecutar instrucción'}</button>{aiMessage && <p className={`mt-2 rounded p-2 text-[11px] ${aiStatus === 'error' ? 'bg-rose-950/50 text-rose-200' : 'bg-slate-800/70 text-slate-300'}`}>{aiMessage}</p>}{aiStatus === 'aclaracion' && <p className="mt-2 text-[11px] text-amber-200">Aclara la instrucción en el campo y vuelve a enviarla.</p>}{aiStatus === 'confirmacion' && <div className="mt-2 flex gap-2"><button onClick={onConfirmAi} className="flex-1 rounded bg-amber-600 px-2 py-2 text-xs font-bold text-white">Confirmar</button><button onClick={onCancelAi} className="rounded border border-slate-600 px-2 py-2 text-xs">Cancelar</button></div>}{aiPlan?.summary && aiStatus === 'confirmacion' && <p className="mt-2 text-[11px] text-amber-100">{aiPlan.summary}</p>}</section>
      <section className="rounded-xl border border-slate-700 bg-[#101a31] p-3"><SectionTitle title="Generador Spring Boot" hint="4 capas" /><ul className="space-y-2 font-mono text-slate-400"><li>✓ 1. Entidades <small className="float-right">@Entity</small></li><li>✓ 2. Repositorios <small className="float-right">JpaRepository</small></li><li>✓ 3. Servicios <small className="float-right">@Service</small></li><li>✓ 4. Controladores <small className="float-right">@RestController</small></li></ul><button onClick={onGenerate} disabled={generating} className="mt-4 w-full rounded-lg border border-indigo-400/40 bg-indigo-600 px-3 py-2 font-bold text-white hover:bg-indigo-500 disabled:cursor-wait disabled:opacity-60">{generating ? 'Generando…' : 'Generar código'}</button></section>
    </div>
    <Presence members={onlineMembers} />
    <div className="flex justify-between border-t border-[#1d2a4a] px-4 py-3 font-mono text-[11px] text-slate-500"><span>{nodes.length} Entidades • {edges.length} Relación{edges.length === 1 ? '' : 'es'}</span><span className="text-emerald-400">Auto-saved</span></div>
  </aside>;
}

function Presence({ members }) {
  const colors = ['bg-emerald-400 shadow-[0_0_8px_#34d399]', 'bg-sky-400 shadow-[0_0_8px_#38bdf8]', 'bg-violet-400 shadow-[0_0_8px_#a78bfa]'];
  return <div className="border-t border-[#1d2a4a] bg-[#0b1429] p-3"><div className="rounded-2xl border border-slate-700/80 bg-[#0a1328] p-3"><div className="mb-3 flex justify-between font-mono text-[11px] font-bold uppercase tracking-wide text-slate-400"><span>Presencia en el lienzo</span><span className="text-emerald-400">{members.length} en línea</span></div><div className="space-y-3 text-xs">{members.map((member, index) => { const user = member.usuario || member; const name = user.username || user.email || 'Usuario'; return <div className="flex items-center gap-2" key={user.id || name}><i className={`h-3 w-3 rounded-full ${colors[index % colors.length]}`} /><span className="min-w-0 flex-1 truncate font-medium text-slate-200">{name} <span className="text-slate-400">({member.rol || 'Colaborador'})</span></span><span className="font-mono text-[10px] text-indigo-300">En lienzo</span></div>; })}{members.length === 0 && <p className="text-xs text-slate-500">No hay personas conectadas.</p>}</div></div></div>;
}
function SectionTitle({ title, hint }) { return <div className="mb-2 flex justify-between font-mono text-[11px] font-bold uppercase tracking-wide text-slate-400"><span>{title}</span><span className="normal-case text-indigo-400">{hint}</span></div>; }
