import { useMemo, useState } from 'react';
import { FiArchive, FiClock, FiCopy, FiFileText, FiFolder, FiMoreVertical, FiPlus, FiSearch, FiUsers, FiX } from 'react-icons/fi';

const tabs = [['all', 'Todos'], ['recent', 'Recientes'], ['mine', 'Mis proyectos'], ['shared', 'Compartidos'], ['templates', 'Plantillas']];
const projectName = (project) => project.nombre || project.name || 'Proyecto sin nombre';
const ownerIdOf = (project) => project.propietario?.id || project.owner?.id || project.creado_por?.id || project.created_by?.id;
const isPendingInvite = (project) => ['pendiente', 'pending'].includes(String(project.estado_invitacion || project.invitation_status || project.estado || '').toLowerCase()) || Boolean(project.invitacion_pendiente || project.invitation_pending);
const isTemplate = (project) => Boolean(project.es_plantilla || project.is_template);
const isShared = (project, currentUserId) => Boolean(project.miembros?.length || project.members?.length) && String(ownerIdOf(project) || '') !== String(currentUserId || '');
const dateOf = (project) => new Date(project.actualizado_en || project.updated_at || project.modificado_en || project.created_at || 0).getTime();
const countNodes = (project) => project.nodes?.length || project.diagrama_principal?.nodes?.length || 0;
const countEdges = (project) => project.edges?.length || project.diagrama_principal?.edges?.length || 0;

export default function ProjectsDialog({ projects, activeId, currentUserId, onClose, onNew, onOpen, onDuplicate, onLeaveProject }) {
  const [query, setQuery] = useState('');
  const [tab, setTab] = useState('all');
  const [sort, setSort] = useState('recent');
  const pendingInvites = useMemo(() => projects.filter(isPendingInvite), [projects]);
  const visibleProjects = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();
    const filtered = projects.filter((project) => {
      if (isPendingInvite(project)) return false;
      if (tab === 'mine' && String(ownerIdOf(project) || '') !== String(currentUserId || '')) return false;
      if (tab === 'shared' && !isShared(project, currentUserId)) return false;
      if (tab === 'templates' && !isTemplate(project)) return false;
      if (tab === 'recent' && !dateOf(project)) return false;
      return !normalizedQuery || projectName(project).toLowerCase().includes(normalizedQuery);
    });
    return filtered.sort((a, b) => sort === 'name' ? projectName(a).localeCompare(projectName(b)) : dateOf(b) - dateOf(a));
  }, [currentUserId, projects, query, sort, tab]);

  return <div className="fixed inset-0 z-40 grid place-items-center bg-[#030715]/80 p-4 backdrop-blur-sm">
    <section className="flex max-h-[92vh] w-full max-w-6xl flex-col overflow-hidden rounded-2xl border border-indigo-400/45 bg-[#0d1830] shadow-2xl shadow-indigo-950/50">
      <header className="flex items-center justify-between border-b border-slate-700/80 px-6 py-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl border border-indigo-400/40 bg-indigo-500/15 text-indigo-300"><FiClock /></span><div><div className="flex items-center gap-2"><h2 className="text-lg font-bold text-white">Historial de Proyectos</h2><span className="rounded-full bg-indigo-500/20 px-2 py-1 text-[10px] font-bold text-indigo-200">DiagramCraft Cloud</span></div><p className="text-sm text-slate-400">Explora, abre o gestiona tus diagramas y esquemas JPA en DiagramCraft Studio.</p></div></div><div className="flex items-center gap-3"><button onClick={onNew} className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-indigo-600 to-violet-600 px-4 py-2.5 text-sm font-bold text-white hover:from-indigo-500 hover:to-violet-500"><FiPlus /> Nuevo Proyecto</button><button onClick={onClose} aria-label="Cerrar historial" className="rounded p-2 text-slate-400 hover:bg-slate-700 hover:text-white"><FiX /></button></div></header>
      <div className="flex flex-wrap items-center gap-3 border-b border-slate-700/80 px-6 py-3"><div className="flex min-w-52 flex-1 items-center gap-2 rounded-lg border border-slate-600 bg-[#091329] px-3"><FiSearch className="text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nombre o entidad..." className="w-full bg-transparent py-2 text-sm outline-none placeholder:text-slate-500" /></div><div className="flex max-w-full gap-1 overflow-x-auto">{tabs.map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold ${tab === key ? 'bg-indigo-600 text-white' : 'bg-[#17233f] text-slate-300 hover:bg-slate-700'}`}>{label}{key === 'shared' && pendingInvites.length > 0 ? <span className="ml-1 rounded bg-amber-400/25 px-1.5 py-0.5 text-amber-200">{pendingInvites.length} pendientes</span> : null}</button>)}</div><select value={sort} onChange={(event) => setSort(event.target.value)} className="rounded-lg border border-slate-600 bg-[#17233f] px-3 py-2 text-xs font-bold text-slate-200 outline-none"><option value="recent">Ordenar: Última edición</option><option value="name">Ordenar: Nombre</option></select></div>
      <main className="min-h-0 flex-1 space-y-5 overflow-auto p-6">{pendingInvites.length > 0 && <section><div className="mb-3 flex flex-wrap items-center justify-between gap-2 border-b border-indigo-400/25 pb-3"><h3 className="flex items-center gap-2 font-bold text-amber-200"><span className="h-2.5 w-2.5 rounded-full bg-amber-400" /> Invitaciones pendientes de colaborar <span className="rounded-full bg-amber-400/20 px-2 py-0.5 text-xs">{pendingInvites.length} nuevas</span></h3><span className="text-xs text-slate-400">Acepta una invitación para abrir el lienzo compartido.</span></div><div className="space-y-3">{pendingInvites.map((project) => <ProjectCard key={project.id} project={project} pending onOpen={onOpen} />)}</div></section>}{pendingInvites.length > 0 && visibleProjects.length > 0 && <div className="flex items-center gap-3 text-[10px] font-bold uppercase tracking-widest text-slate-500"><i className="h-px flex-1 bg-slate-700" /> Proyectos disponibles <i className="h-px flex-1 bg-slate-700" /></div>}<section className="space-y-3">{visibleProjects.map((project) => <ProjectCard key={project.id} project={project} active={project.id === activeId} shared={isShared(project, currentUserId)} onOpen={onOpen} onDuplicate={onDuplicate} />)}{visibleProjects.length === 0 && <div className="rounded-xl border border-dashed border-slate-600 p-10 text-center text-sm text-slate-400">No hay proyectos para este filtro.</div>}</section></main>
      <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-700/80 px-6 py-4 text-xs text-slate-400"><span><b className="text-emerald-300">●</b> {projects.length} proyectos disponibles · Sincronización en la nube activa</span><div className="flex items-center gap-4"><span className="flex items-center gap-1"><FiArchive /> Papelera / Archivados</span><span className="flex items-center gap-1"><FiUsers /> Proyectos compartidos</span>{activeId && <button onClick={onLeaveProject} className="rounded border border-slate-600 px-3 py-1.5 font-bold text-slate-200 hover:border-rose-400 hover:text-rose-200">Salir del proyecto</button>}</div></footer>
    </section>
  </div>;
}

function ProjectCard({ project, active, shared, pending, onOpen, onDuplicate }) {
  const owner = project.propietario || project.owner || project.invitado_por || project.invited_by;
  const role = project.rol || project.role || project.rol_invitacion || project.invitation_role;
  return <article className={`flex flex-wrap items-center gap-4 rounded-xl border p-4 ${active ? 'border-indigo-400 bg-indigo-500/10' : pending ? 'border-violet-400/65 bg-[#121b3b]' : 'border-slate-700 bg-[#0b1529]'}`}><span className={`grid h-11 w-11 place-items-center rounded-xl ${pending ? 'bg-violet-500/25 text-violet-200' : 'bg-indigo-600/30 text-indigo-200'}`}>{pending ? <FiUsers /> : <FiFolder />}</span><div className="min-w-48 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-white">{projectName(project)}</h3>{active && <span className="rounded-full bg-emerald-500/15 px-2 py-1 text-[10px] text-emerald-300">● Activo en lienzo</span>}{pending && <span className="rounded-full bg-amber-400/15 px-2 py-1 text-[10px] text-amber-200">Invitación pendiente</span>}{shared && !pending && <span className="rounded-full bg-cyan-400/15 px-2 py-1 text-[10px] text-cyan-200">Colaborador activo</span>}</div><p className="mt-1 font-mono text-[11px] text-slate-400">Spring Boot 3.2 · JPA Hibernate</p>{owner && <p className="mt-1 text-xs text-slate-400">Invitado por <b className="text-slate-200">{owner.username || owner.email || owner.nombre}</b>{role ? ` · Rol: ${role}` : ''}</p>}<p className="mt-2 flex gap-3 text-xs text-slate-400"><span><FiFileText className="mr-1 inline" />{countNodes(project)} Entidades</span><span>⌁ {countEdges(project)} Relaciones</span></p></div><div className="flex items-center gap-2">{pending ? <><button title="Requiere endpoint de rechazar invitación" className="rounded-lg border border-slate-600 px-3 py-2 text-xs font-bold text-slate-300">Rechazar</button><button onClick={() => onOpen(project)} title="El backend debe aceptar la invitación antes de abrir" className="rounded-lg bg-gradient-to-r from-indigo-600 to-violet-600 px-3 py-2 text-xs font-bold text-white">Aceptar y abrir</button></> : <><button onClick={() => onDuplicate?.(project)} title="Duplicar" className="rounded-lg border border-slate-600 p-2.5 hover:bg-slate-700"><FiCopy /></button><button onClick={() => onOpen(project)} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm font-bold hover:bg-indigo-500">Abrir</button><button className="rounded p-2 text-slate-400 hover:bg-slate-700"><FiMoreVertical /></button></>}</div></article>;
}
