import { useMemo, useState } from 'react';
import { FiCopy, FiFileText, FiFolder, FiLogOut, FiMoreVertical, FiPlus, FiSearch, FiUsers, FiX } from 'react-icons/fi';

export default function ProjectsDialog({ projects, activeId, onClose, onNew, onOpen, onDuplicate, onLeaveProject }) {
  const [query, setQuery] = useState('');
  const shown = useMemo(() => projects.filter((project) => (project.name || project.nombre || '').toLowerCase().includes(query.toLowerCase())), [projects, query]);

  return <div className="fixed inset-0 z-40 grid place-items-center bg-[#030715]/80 p-4 backdrop-blur-sm">
    <section className="w-full max-w-5xl overflow-hidden rounded-2xl border border-indigo-400/35 bg-[#101a31] shadow-2xl">
      <header className="flex items-center justify-between border-b border-slate-700 px-6 py-5">
        <div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl border border-indigo-400/40 bg-indigo-500/15 text-indigo-300"><FiFolder /></span><div><h2 className="text-lg font-bold text-white">Historial de Proyectos</h2><p className="text-sm text-slate-400">Explora, abre o gestiona tus diagramas y esquemas JPA en DiagramCraft Studio.</p></div></div>
        <div className="flex items-center gap-3"><button onClick={onNew} className="flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-indigo-500"><FiPlus /> Nuevo Proyecto</button>{activeId && <button onClick={onLeaveProject} className="flex items-center gap-2 rounded-lg border border-slate-600 px-4 py-2.5 text-sm font-bold text-slate-200 hover:border-rose-400 hover:bg-rose-500/10 hover:text-rose-200"><FiLogOut className="text-rose-300" /> Salir del proyecto</button>}<button onClick={onClose} className="rounded p-2 text-slate-400 hover:bg-slate-700"><FiX /></button></div>
      </header>
      <div className="flex items-center gap-3 border-b border-slate-700 px-6 py-4"><div className="flex flex-1 items-center gap-2 rounded-lg border border-slate-600 bg-[#0a1328] px-3"><FiSearch className="text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nombre o entidad..." className="w-full bg-transparent py-2 text-sm outline-none placeholder:text-slate-500" /></div><span className="rounded bg-indigo-600 px-3 py-2 text-xs font-bold">Todos ({projects.length})</span></div>
      <main className="max-h-[55vh] space-y-3 overflow-auto p-6">{shown.map((project) => <article key={project.id} className={`flex items-center gap-4 rounded-xl border p-4 ${project.id === activeId ? 'border-indigo-400 bg-indigo-500/10' : 'border-slate-700 bg-[#0c162c]'}`}><span className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-600/30 text-indigo-300"><FiFolder /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="truncate font-bold text-white">{project.nombre || project.name}</h3>{project.id === activeId && <span className="rounded-full bg-emerald-500/15 px-2 py-1 text-[10px] text-emerald-300">● Activo en lienzo</span>}</div><p className="mt-1 font-mono text-[11px] text-slate-400">Spring Boot 3.2 · JPA Hibernate</p><p className="mt-2 flex gap-3 text-xs text-slate-400"><span><FiFileText className="mr-1 inline" />{project.nodes?.length || 0} Entidades</span><span>⌁ {project.edges?.length || 0} Relaciones</span></p></div><div className="flex gap-2"><button onClick={() => onDuplicate(project)} title="Duplicar" className="rounded-lg border border-slate-600 p-2.5 hover:bg-slate-700"><FiCopy /></button><button onClick={() => onOpen(project)} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm font-bold hover:bg-indigo-500">Abrir</button><button className="rounded p-2 text-slate-400 hover:bg-slate-700"><FiMoreVertical /></button></div></article>)}{shown.length === 0 && <p className="py-10 text-center text-sm text-slate-400">No hay proyectos que coincidan con la búsqueda.</p>}</main>
      <footer className="flex items-center justify-between border-t border-slate-700 px-6 py-4 text-xs text-slate-400"><span><b className="text-emerald-300">●</b> {projects.length} proyectos disponibles</span><span className="flex items-center gap-2"><FiUsers /> Proyectos compartidos</span></footer>
    </section>
  </div>;
}
