import { FiPlus, FiTrash2, FiX } from 'react-icons/fi';
import { useEscapeClose } from '../../hooks/useEscapeClose';
export default function PropertiesPanel({ node, position, onClose, onUpdate, onAddAttribute, onUpdateAttribute, onRemoveAttribute, onAddMethod, onUpdateMethod, onRemoveMethod, onDelete }) {
  useEscapeClose(Boolean(node), onClose);
  if (!node) return null;
  const title = node.data.title.replace(/\.java$/, '');
  const style = position ? { left: Math.min(Math.max(12, position.x), window.innerWidth - 340), top: Math.min(Math.max(12, position.y), window.innerHeight - 520) } : undefined;
  return <aside style={style} aria-label="Editar campos y métodos" className={`fixed z-30 w-80 rounded-xl border border-slate-700 bg-[#101a31] p-4 text-xs text-slate-200 shadow-2xl ${position ? '' : 'right-4 top-4'}`}><div className="mb-4 flex items-center justify-between"><b className="text-sm">Editar campos y métodos</b><button onClick={onClose} className="rounded p-1 hover:bg-slate-700"><FiX /></button></div><label className="mb-1 block text-slate-400">Nombre de entidad</label><input value={title} onChange={(e) => onUpdate({ title: `${e.target.value}.java` })} className="mb-3 w-full rounded border border-slate-600 bg-[#080f20] px-3 py-2 outline-none focus:border-indigo-400" /><label className="mb-4 block text-slate-400">Tipo<select value={node.data.kind || 'entity'} onChange={(event) => onUpdate({ kind: event.target.value })} className="mt-1 w-full rounded border border-slate-600 bg-[#080f20] px-3 py-2"><option value="entity">@Entity</option><option value="dto">DTO</option><option value="enum">enum</option><option value="embeddable">@Embeddable</option></select></label>
    <div className="mb-2 flex items-center justify-between"><b>Atributos</b><button onClick={onAddAttribute} className="flex items-center gap-1 rounded bg-indigo-600 px-2 py-1 hover:bg-indigo-500"><FiPlus /> Añadir</button></div><div className="max-h-60 space-y-2 overflow-auto">{node.data.properties.map((attr, index) => <div key={index} className="flex gap-1"><input aria-label="Nombre" value={attr.name} onChange={(e) => onUpdateAttribute(index, { name: e.target.value })} className="min-w-0 flex-1 rounded border border-slate-700 bg-[#080f20] px-2 py-1.5" /><input aria-label="Tipo" value={attr.type} onChange={(e) => onUpdateAttribute(index, { type: e.target.value })} className="w-24 rounded border border-slate-700 bg-[#080f20] px-2 py-1.5" /><button onClick={() => onRemoveAttribute(index)} className="rounded px-1 text-rose-300 hover:bg-rose-500/20"><FiTrash2 /></button></div>)}</div>
    <div className="mb-2 mt-4 flex items-center justify-between"><b>Métodos</b><button onClick={onAddMethod} className="flex items-center gap-1 rounded bg-indigo-600 px-2 py-1 hover:bg-indigo-500"><FiPlus /> Añadir</button></div><div className="max-h-36 space-y-2 overflow-auto">{(node.data.methods || []).map((method, index) => <div key={index} className="flex gap-1"><input aria-label="Método" value={method} onChange={(event) => onUpdateMethod(index, event.target.value)} className="min-w-0 flex-1 rounded border border-slate-700 bg-[#080f20] px-2 py-1.5" /><button onClick={() => onRemoveMethod(index)} className="rounded px-1 text-rose-300 hover:bg-rose-500/20"><FiTrash2 /></button></div>)}</div><button onClick={onDelete} className="mt-5 flex w-full items-center justify-center gap-2 rounded border border-rose-500/50 px-3 py-2 text-rose-300 hover:bg-rose-500/15"><FiTrash2 /> Eliminar entidad</button></aside>;
}
