import { useEffect, useMemo, useRef, useState } from 'react';
import { FiCheck, FiClock, FiCopy, FiEye, FiLink, FiMail, FiRefreshCw, FiSend, FiSliders, FiTrash2, FiUsers, FiX } from 'react-icons/fi';
import { useEscapeClose } from '../../hooks/useEscapeClose';

const roles = [{ value: 'editor', label: 'Editor de Diagrama' }, { value: 'arquitecto', label: 'Arquitecto' }, { value: 'lector', label: 'Solo lectura' }];
const pendingInvitations = (project) => project?.invitaciones_pendientes || [];

export default function CollaboratorsDialog({ project, email, setEmail, onlineMembers = [], acceptedMember, onDismissAccepted, onClose, onInvite, onResendInvite, onCancelInvite, onChangeRole, onRemove, onViewCanvas, currentUserId, canInvite, canManage }) {
  useEscapeClose(true, onClose);
  const [role, setRole] = useState('editor');
  const [copied, setCopied] = useState(false);
  const roomLink = useMemo(() => `${window.location.origin}/proyecto/${project?.id || 'nuevo'}/live-canvas`, [project?.id]);
  const invitations = pendingInvitations(project);
  const submit = (event) => { event.preventDefault(); onInvite(role); };
  const copyLink = async () => { try { await navigator.clipboard.writeText(roomLink); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { setCopied(false); } };
  return <div className="fixed inset-0 z-40 grid place-items-center bg-[#020617]/75 p-4 backdrop-blur-sm"><section className="w-full max-w-3xl overflow-hidden rounded-2xl border border-indigo-400/35 bg-[#0a1430] text-slate-200 shadow-2xl shadow-black/50">
    <header className="flex items-center gap-3 border-b border-slate-700/80 px-5 py-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 text-lg text-white"><FiUsers /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="font-bold text-white">Colaboradores del Lienzo (Tiempo Real)</h2><span className="rounded-full border border-emerald-400/30 bg-emerald-500/15 px-2 py-0.5 text-[10px] font-bold text-emerald-300">● Sync Activo</span></div><p className="mt-0.5 text-xs text-slate-400">Invita a tu equipo de ingeniería para modelar diagramas simultáneamente.</p></div><button onClick={onClose} aria-label="Cerrar" className="rounded-lg p-2 text-slate-400 hover:bg-slate-700 hover:text-white"><FiX /></button></header>
    <div className="space-y-4 p-5">
      {acceptedMember && <AcceptedInvitation member={acceptedMember} onDismiss={onDismissAccepted} />}
      <form onSubmit={submit} className="grid gap-3 rounded-xl border border-indigo-400/25 bg-[#0d1937] p-3 md:grid-cols-[minmax(0,1fr)_180px_auto]"><label className="block min-w-0"><span className="mb-1 block text-[10px] font-bold uppercase tracking-wide text-slate-400">Invitar por correo electrónico o nombre de usuario</span><input disabled={!canInvite} value={email} onChange={(event) => setEmail(event.target.value)} required placeholder="ej. kelly.dev@empresa.com o usuario" className="w-full rounded-lg border border-slate-600 bg-[#071025] px-3 py-2.5 text-sm outline-none placeholder:text-slate-500 focus:border-indigo-400 disabled:opacity-45" /></label><label className="block"><span className="mb-1 block text-[10px] font-bold uppercase tracking-wide text-slate-400">Permisos granulares JPA</span><select disabled={!canInvite} value={role} onChange={(event) => setRole(event.target.value)} className="w-full rounded-lg border border-slate-600 bg-[#071025] px-3 py-2.5 text-sm outline-none focus:border-indigo-400 disabled:opacity-45">{roles.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><button disabled={!canInvite} className="mt-auto flex items-center justify-center gap-2 rounded-lg bg-gradient-to-r from-indigo-600 to-violet-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-45"><FiSend /> Enviar invitación</button></form>
      <div className="flex flex-col gap-3 rounded-xl border border-slate-700 bg-[#0d1937] p-3 md:flex-row md:items-end"><div className="min-w-0 flex-1"><div className="mb-1 flex items-center gap-2 text-[10px] font-bold uppercase tracking-wide text-slate-400"><FiLink className="text-cyan-300" /> Enlace de sesión en vivo (WebSocket room)<span className="ml-auto normal-case text-slate-500">Acceso: cualquiera con enlace puede editar</span></div><div className="truncate rounded-lg border border-slate-600 bg-[#071025] px-3 py-2 font-mono text-xs text-slate-300">{roomLink}</div></div><button type="button" onClick={copyLink} className="flex items-center justify-center gap-2 rounded-lg border border-slate-600 bg-[#172544] px-4 py-2.5 text-sm font-bold hover:border-indigo-400 hover:bg-indigo-500/20">{copied ? <FiCheck className="text-emerald-300" /> : <FiCopy />} {copied ? 'Copiado' : 'Copiar enlace'}</button></div>
      <section style={{ borderColor: invitations.length ? '#695221' : '#23365f', backgroundColor: '#101a34' }} className="rounded-xl border p-3"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 text-xs font-extrabold text-amber-200"><FiClock /> Invitaciones pendientes ({invitations.length}) <span className="rounded bg-slate-700 px-2 py-1 font-mono text-[10px] text-slate-300">{invitations.length ? 'Esperando que acepte' : 'Sin pendientes'}</span></h3><span className="text-[10px] italic text-slate-400">{invitations.length ? 'Solicitud enviada' : 'Todas las solicitudes han sido resueltas'}</span></div>{invitations.length > 0 && <div className="mt-3 space-y-2">{invitations.map((invitation) => <PendingInvitation key={invitation.id} invitation={invitation} onResend={() => onResendInvite(invitation)} onCancel={() => onCancelInvite(invitation)} />)}</div>}</section>
      <section><div className="mb-2 flex items-center justify-between"><h3 className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-slate-300"><FiUsers className="text-violet-300" /> Miembros del equipo / colaboradores activos ({project?.miembros?.length || 0})</h3><span className="font-mono text-[10px] text-emerald-400">STOMP/WS Sincronizado</span></div><div className="space-y-2">{(project?.miembros || []).map((member) => <Member key={member.id} member={member} isCurrent={String(member.usuario?.id) === String(currentUserId)} isOnline={onlineMembers.some((online) => String((online.usuario || online).id) === String(member.usuario?.id))} onChangeRole={onChangeRole} onRemove={onRemove} onViewCanvas={onViewCanvas} canManage={canManage} />)}{!project?.miembros?.length && <p className="rounded-xl border border-slate-700 bg-[#0c1731] p-4 text-center text-xs text-slate-400">Aún no hay miembros registrados para este proyecto.</p>}</div></section>
    </div>
    <footer className="flex items-center justify-between border-t border-slate-700/80 px-5 py-3 text-[11px] text-slate-400"><span><i className="mr-2 text-amber-300">♦</i>Las invitaciones pendientes no cuentan como miembros.</span><button onClick={onClose} className="rounded-lg bg-slate-700 px-3 py-1.5 font-bold text-slate-200 hover:bg-slate-600">Entendido</button></footer>
  </section></div>;
}

function AcceptedInvitation({ member, onDismiss }) {
  const [visible, setVisible] = useState(true);
  const dismissRef = useRef(onDismiss);
  useEffect(() => { dismissRef.current = onDismiss; }, [onDismiss]);
  useEffect(() => {
    const fadeTimer = window.setTimeout(() => setVisible(false), 3200);
    const dismissTimer = window.setTimeout(() => dismissRef.current?.(), 3600);
    return () => {
      window.clearTimeout(fadeTimer);
      window.clearTimeout(dismissTimer);
    };
  }, [member]);
  const user = member.usuario || member;
  const name = user.email || user.username || 'El colaborador';
  return <div className={`flex items-center gap-3 rounded-xl border border-emerald-400/55 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-100 transition-opacity duration-300 ${visible ? 'opacity-100' : 'opacity-0'}`}><span className="grid h-7 w-7 place-items-center rounded-full bg-emerald-500/20 text-emerald-300"><FiCheck /></span><p className="min-w-0 flex-1"><b className="text-white">{name}</b> ha aceptado la invitación y se ha unido al lienzo.</p><button onClick={onDismiss} className="rounded p-1 text-emerald-200 hover:bg-emerald-500/15"><FiX /></button></div>;
}

function PendingInvitation({ invitation, onResend, onCancel }) {
  const invited = invitation.invitado || invitation.invitee || invitation.usuario || {};
  const name = invited.email || invited.username || 'Usuario invitado';
  const sentAt = invitation.fecha ? new Intl.DateTimeFormat('es-BO', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(invitation.fecha)) : 'Recién enviada';
  const role = roles.find((item) => item.value === invitation.rol)?.label || invitation.rol || 'Editor de Diagrama';
  return <article style={{ borderColor: '#23365f', backgroundColor: '#152346' }} className="flex items-center gap-3 rounded-xl border px-3 py-3"><span style={{ borderColor: '#6f5927', backgroundColor: '#252332', color: '#f2c95c' }} className="grid h-11 w-11 shrink-0 place-items-center rounded-full border-2"><FiMail /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b className="truncate text-sm text-white">{name}</b><span style={{ backgroundColor: '#3a3485' }} className="rounded px-2 py-1 font-mono text-[10px] font-bold text-indigo-200">{role}</span></div><span style={{ backgroundColor: '#6e4308', color: '#ffd36b' }} className="mt-1 inline-block rounded px-2 py-1 text-[10px] font-bold">● Pendiente de aceptación</span><div className="mt-1 flex flex-wrap gap-x-4 text-[10px]"><span className="text-slate-300">Enviada: {sentAt}</span><span className="text-slate-400">• Expira en 7 días</span><span style={{ color: '#e3bb4d' }} className="font-bold italic">• Esperando respuesta del colaborador</span></div></div><div className="flex shrink-0 gap-2"><button type="button" onClick={onResend} style={{ borderColor: '#344b7d', backgroundColor: '#17294f' }} className="flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold text-slate-200"><FiRefreshCw /> Reenviar</button><button type="button" onClick={onCancel} style={{ borderColor: '#344b7d', backgroundColor: '#17294f' }} className="flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold text-rose-300"><FiX /> Cancelar</button></div></article>;
}

function Member({ member, isCurrent, isOnline, onChangeRole, onRemove, onViewCanvas, canManage }) {
  const user = member.usuario || {}; const name = user.username || user.email || 'Usuario'; const initials = name.slice(0, 2).toUpperCase();
  const role = roles.find((item) => item.value === member.rol)?.label || member.rol || 'Colaborador';
  return <article className="flex min-h-[94px] items-center gap-3 rounded-xl border border-emerald-400/55 bg-[#0c1731] p-3 shadow-[0_0_14px_rgba(16,185,129,0.12)]"><span className="relative grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-emerald-500 text-xs font-bold text-white shadow-lg shadow-emerald-950/60">{initials}<i className={`absolute -bottom-1 -right-1 h-3 w-3 rounded-full border-2 border-[#0c1731] ${isOnline ? 'bg-emerald-400' : 'bg-slate-500'}`} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sm text-white">{name}</b><span className="max-w-44 truncate text-xs text-slate-400">({user.email || 'sin correo'})</span><span className="rounded bg-indigo-500/30 px-2 py-1 font-mono text-[10px] font-bold text-indigo-200">{role}</span>{isCurrent && <span className="text-[10px] text-sky-300">Tú</span>}</div><div className="mt-1 flex flex-wrap gap-2"><span className="flex items-center gap-1 rounded-full bg-emerald-500/15 px-2 py-1 text-[10px] font-bold text-emerald-300"><FiCheck /> Invitación aceptada</span>{isOnline && <span className="rounded-full bg-emerald-500/15 px-2 py-1 text-[10px] font-bold text-emerald-300">● En línea ahora (Cursor activo)</span>}</div><p className="mt-1 text-[10px] text-slate-400">Unido recientemente</p></div><div className="flex shrink-0 items-center gap-2"><button type="button" onClick={onViewCanvas} className="hidden min-h-[42px] rounded-lg border border-indigo-400/35 bg-indigo-500/15 px-3 text-xs font-bold text-indigo-200 hover:bg-indigo-500/25 sm:flex sm:items-center sm:gap-2"><FiEye /> Ver en<br />lienzo</button>{canManage && <select value={member.rol} onChange={(event) => onChangeRole(member, event.target.value)} className="rounded-lg border border-slate-600 bg-[#172544] px-2 py-2 text-[10px] text-slate-200"><option value="arquitecto">Arquitecto</option><option value="editor">Editor</option><option value="lector">Solo lectura</option></select>}<button title="Controles del colaborador" className="grid h-10 w-10 place-items-center rounded-lg border border-slate-600 bg-[#172544] text-slate-300"><FiSliders /></button>{canManage && !isCurrent && <button onClick={() => onRemove(member)} title="Eliminar colaborador" className="rounded p-2 text-rose-300 hover:bg-rose-500/15"><FiTrash2 /></button>}</div></article>;
}
